version: "3"
services:
  db:
    image: postgres:15-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    user: 1000:1000
  back:
    build:
      context: ./back/back.web
      dockerfile: Dockerfile.dev
    volumes:
      - ./back/back.web:/app
    container_name: back
    restart: always
    depends_on:
      - db
    ports:
      - 5225:5225
    command: dotnet watch run --launch-profile publicdev
  front:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    volumes:
      - ./front/src:/app/src
    container_name: front
    restart: always
    depends_on:
      - back
    ports:
      - 4200:4200
    command: ng serve --host 0.0.0.0
