version: "3.8"
services:
  db:
    image: postgres:15-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
    user: 1000:1000
  back:
    build:
      context: ./back/back.web
      dockerfile: Dockerfile.prod
    container_name: back
    restart: always
    depends_on:
      - db
  front:
    build:
      context: ./front
      dockerfile: Dockerfile.prod
    container_name: front
    restart: always
    depends_on:
      - back
    environment:
    	- API_URL:"http:://planningpoker.azurewebsites.net"
