version: "3"
services:
  db:
    image: postgres:15-alpine
    volumes:
      - ./db:/var/lib/postgresql/data
    container_name: db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PORT=5432
  back:
    build:
      context: ./back/back.web
      dockerfile: Dockerfile
    container_name: back
    restart: always
    ports:
      - "80:80"
  front:
    build:
      context: ./front
      dockerfile: Dockerfile.dev
    container_name: front
    restart: always
    volumes:
      - ./front/src:/app/src
    ports:
      - "4200:4200"
    command: ng serve --host 0.0.0.0
