name: cd

on:
  push:
    branches:
      - main

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push back
        uses: docker/build-push-action@v4
        with:
          context: ./back/back.web
          file: ./back/back.web/Dockerfile.prod
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tsd-project-back:latest
      -
        name: Build and push front
        uses: docker/build-push-action@v4
        with:
          context: ./front
          file: ./front/Dockerfile.prod
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tsd-project-front:latest
      -
        name: Build and push rv-proxy
        uses: docker/build-push-action@v4
        with:
          context: ./rv-proxy
          file: ./rv-proxy/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tsd-project-rv-proxy:latest
