name: ci

on:
  push:
    branches-ignore: main

jobs:
  test-back:
    defaults:
      run:
        working-directory: back

    runs-on: ubuntu-latest

    permissions:
      checks: write

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0'
      - name: Install dependencies
        run: dotnet restore
      - name: Test with dotnet
        run: dotnet test --logger trx --results-directory TestResults
      - name: Test Report  # https://github.com/marketplace/actions/test-reporter
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: MSTest Tests
          path: back/TestResults/*.trx
          reporter: dotnet-trx

  test-front:
    defaults:
      run:
        working-directory: front

    runs-on: ubuntu-latest

    permissions:
      checks: write

    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test:ci
      - name: Test Report
        uses: mikepenz/action-junit-report@v3
        if: success() || failure()
        with:
          report_paths: 'front/TestResults/*.xml'
